In [1]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
# Binary classification
class NeuralNet1(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet1, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)  
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # sigmoid at the end
        y_pred = torch.sigmoid(out)
        return y_pred

In [ ]:
model = NeuralNet1(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()

In [ ]:
# Multiclass problem
class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # no softmax at the end for cross entropy
        return out

In [ ]:
model = NeuralNet2(input_size = 28*28, hidden_size = 5, num_classes = 3)
criterion = nn.CrossEntropyLoss()

In [3]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim = 0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [4]:
loss = nn.CrossEntropyLoss()

In [9]:
Y = torch.tensor([2, 0, 1])
# nsamples x nclasses = 3 x 3
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])

In [10]:
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

In [11]:
print(l1.item())
print(l2.item())

0.3018244206905365
1.6241613626480103


In [12]:
_, preds1 = torch.max(Y_pred_good, 1)
_, preds2 = torch.max(Y_pred_bad, 1)

print(preds1)
print(preds2)

tensor([2, 0, 1])
tensor([0, 2, 1])
