In [1]:
import torch

In [3]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([1.4132, 0.4282, 1.8285], requires_grad=True)


In [4]:
y = x+2
print(y)

tensor([3.4132, 2.4282, 3.8285], grad_fn=<AddBackward0>)


In [7]:
z = y*y*2
#z = z.mean()
print(z)

tensor([23.2993, 11.7920, 29.3150], grad_fn=<MulBackward0>)


In [8]:
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
z.backward(v)
print(x.grad)

tensor([ 5.9161, 12.9502,  5.1200])


In [ ]:
#####

In [9]:
x = torch.randn(3, requires_grad=True)

In [10]:
### To remove the gradients to prevent history tracking ###

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

In [11]:
x.requires_grad_(False)
print(x)

tensor([ 0.8189,  0.7376, -0.4287])


In [12]:
y = x.detach()
print(y)

tensor([ 0.8189,  0.7376, -0.4287])


In [13]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.8189, 2.7376, 1.5713])


In [20]:
### emptying the gradients ###

#weights.grad.zero_()

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    
    model_output = (weights*3).sum()
    model_output.backward()
    
    #weights.grad.zero_()
    
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [17]:
model_output

tensor(12., grad_fn=<SumBackward0>)